data: document diacritics use in the different languages
zladx/LADX-Disassembly pull request #459
Opened 2022-10-16 21:30 UTC by kemenaran

- Separate the diacritics table and the ascii table
- Document the diacritics of each language

2022-10-16 21:47 UTC, tobiasvl commented
Should the diacritics file perhaps be named `ascii_to_diacritic.asm`, to be consistent with `ascii_to_tile.asm` and to make it clear that it maps an ASCII character to the corresponding diacritic which is harder to understand now that it's no longer directly beneath the ASCII-to-tile table?

Or maybe `diacritics.asm` could have a short explanatory text on the top which explains this. Maybe even `ascii_to_tile.asm` should have a short text (in the non-English versions) that explains how diacritics work, since otherwise it might be a bit confusing to see that the ASCII character Ä maps to the tile A, with no explanation on how the umlauts get there.

2022-10-17 07:46 UTC, tobiasvl commented
Other counter-intuitive things that we could potentially document here:
* The diacritics tiles are found in https://github.com/zladx/LADX-Disassembly/tree/document-diacritics/tree/main/src/gfx/items/inventory_overworld_items.dmg, which is hard to find on your own
* The value 1 in the `DiacriticsTable` maps to tile `$C9`, while 2 maps to `$C8`, so the order is the opposite of what you might expect

2022-10-17 08:24 UTC, kemenaran commented
Ah, yes, I'll definitely document those two shortcoming.

Also, I wasn't sure about the file naming, because I'm not sure the diacritics table is actually indexed by ascii code – is it really the case?

2022-10-17 11:25 UTC, tobiasvl commented
> Also, I wasn't sure about the file naming, because I'm not sure the diacritics table is actually indexed by ascii code – is it really the case?

Yes.

This is easier to see with my annotations in #460. The ASCII value is put into `bc` [here](https://github.com/zladx/LADX-Disassembly/pull/460/files#diff-c4911341abbe29a19fd64e33beb16a83dc754d0de31a026877edafaa4c9c2953R166) before calling `ReadTileValueFromDiacriticsTable` (called `ReadDialogBankFromTable` before my PR, which is a misnomer), which loads the address to `DiacriticsTable` into `hl` [here](https://github.com/zladx/LADX-Disassembly/pull/460/files#diff-84e4db15124403048717b4b64a1d10dea27c7b756354aaecfe8d2aa406649540R780) before adding `bc` and `hl` together to ultimately get the entry in `DiacriticsTable` indexed by ASCII code and load that value into `a` before returning and using that value to decide what diacritic to use [here](https://github.com/zladx/LADX-Disassembly/pull/460/files#diff-c4911341abbe29a19fd64e33beb16a83dc754d0de31a026877edafaa4c9c2953R182).

2022-10-21 13:52 UTC, tobiasvl requested changes
Suggestions:

* Rename `diacritics.asm` to `ascii_to_diacritic.asm`, to be consistent with `ascii_to_tile.asm`
* Perhaps: Add some text to `ascii_to_tile.asm` for non-English revisions explaining where to find diacritics
* Not sure: Explain what tilesheet (https://github.com/zladx/LADX-Disassembly/tree/document-diacritics/tree/main/src/gfx/items/inventory_overworld_items.dmg) the two diacritics tiles are in

2022-10-21 13:52 UTC, tobiasvl commented on revisions/J0/src/data/diacritics.asm
> +; - 1: ゛
```suggestion
; - 1: ゛ (dakuten, tile $C9)
```

2022-10-21 13:52 UTC, tobiasvl commented on revisions/J0/src/data/diacritics.asm
> +; - 2: ゜
```suggestion
; - 2: ゜ (handakuten, tile $C8)
```

2022-10-21 13:52 UTC, tobiasvl commented on revisions/F0/src/data/diacritics.asm
> +; - 1: ´ (Acute accent on uppercase letter)
```suggestion
; - 1: ´ (Acute accent on uppercase letter, tile $C9)
```

2022-10-21 13:52 UTC, tobiasvl commented on revisions/F0/src/data/diacritics.asm
> +; - 2: ` (Grave accent on uppercase letter)
```suggestion
; - 2: ` (Grave accent on uppercase letter, tile $C8)
```

2022-10-21 13:52 UTC, tobiasvl commented on revisions/G0/src/data/diacritics.asm
> +; - 1: ¨ (umlaut on uppercase letter)
```suggestion
; - 1: ¨ (umlaut on uppercase letter, tile $C9)
```

2022-10-21 13:52 UTC, tobiasvl commented on revisions/G0/src/data/diacritics.asm
> +; - 2: ¨ (umlaut on lowercase letter)
```suggestion
; - 2: ¨ (umlaut on lowercase letter, tile $C8)
```

2022-10-21 13:52 UTC, tobiasvl commented on revisions/J0/src/data/diacritics.asm
> +    db     0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0
Maybe make the table a bit more compact with less whitespace, like in the other revisions?

2022-10-30 20:49 UTC, kemenaran commented
@tobiasvl I finally had some time to work again on this; it should be in better shape now. Thanks for your comments!

2022-10-30 21:44 UTC, tobiasvl approved these changes

2022-10-31 06:20 UTC, merged